select
	Empleado.IdEmpleado ID_EMPLEADO, Empleado.ApellidoPaterno A_PATERNO, Empleado.ApellidoMaterno A_MATERNO, 
	Empleado.Nombre NOMBRE_EMPLEADO, Empleado.Puesto PUESTO ,Empleado.FechaNacimiento F_NACIM, 
	Empleado.FechaAntiguedad F_ANTIG, Empleado.Sexo SEXO, Empleado.Correo EMAIL, 
	Empleado.TipoFuncion TIPO_FUNCION, Empleado.CondicionTrabajo CONDIC_TRAB, Empleado.GradoAcademico GRADO_ACADEM, 
	Empleado.UnidadNegocio UNIDAD_NEGOCIO, Empleado.DivisionMarca DIVIS_MARCA, 
	Empleado.AreaAgencia AREA_AGENCIA, Empleado.Depto DEPARTAMENTO, Empleado.Subdepartamento SUBDEPARTAMENTO,
	Empleado.EmpresaContratante EMP_CONTRATANTE, 
	Empleado.IdResponsableRH ID_RESPONS_RH, 
	Empleado.NombreResponsableRH NOM_RESPONS_RH, Empleado.IdJefe ID_JEFE, 
	Empleado.NombreJefe NOMBRE_JEFE, PuestoJefe PUESTO_JEFE,  
	Empleado.IdResponsableEstructura ID_RESPONS_EST, 
	Empleado.NombreResponsableEstructura NOM_RESP_ESTRUC , 
	Empleado.ClaveAcceso CVE_ACCESO, 
	Empleado.RangoAntiguedad RANGO_ANTIG , Empleado.RangoEdad RANGO_EDAD , 
	EstatusEncuesta.Estatus STS_ENCUESTA , Empleado.EstatusEmpleado ESTATUS_COLABORADOR,
	 
	  max(case when IdPregunta = 1 then RespuestaEmpleado end) EMP_R1,
	  max(case when IdPregunta = 2 then RespuestaEmpleado end) EMP_R2,
	  max(case when IdPregunta = 3 then RespuestaEmpleado end) EMP_R3,
	  max(case when IdPregunta = 4 then RespuestaEmpleado end) EMP_R4,
	  max(case when IdPregunta = 5 then RespuestaEmpleado end) EMP_R5,
	  max(case when IdPregunta = 6 then RespuestaEmpleado end) EMP_R6,
	  max(case when IdPregunta = 7 then RespuestaEmpleado end) EMP_R7,
	  max(case when IdPregunta = 8 then RespuestaEmpleado end) EMP_R8,
	  max(case when IdPregunta = 9 then RespuestaEmpleado end) EMP_R9,
	  max(case when IdPregunta = 10 then RespuestaEmpleado end) EMP_R10,
	  max(case when IdPregunta = 11 then RespuestaEmpleado end) EMP_R11,
	  max(case when IdPregunta = 12 then RespuestaEmpleado end) EMP_R12,
	  max(case when IdPregunta = 13 then RespuestaEmpleado end) EMP_R13,
	  max(case when IdPregunta = 14 then RespuestaEmpleado end) EMP_R14,
	  max(case when IdPregunta = 15 then RespuestaEmpleado end) EMP_R15,
	  max(case when IdPregunta = 16 then RespuestaEmpleado end) EMP_R16,
	  max(case when IdPregunta = 17 then RespuestaEmpleado end) EMP_R17,
	  max(case when IdPregunta = 18 then RespuestaEmpleado end) EMP_R18,
	  max(case when IdPregunta = 19 then RespuestaEmpleado end) EMP_R19,
	  max(case when IdPregunta = 20 then RespuestaEmpleado end) EMP_R20,

	  max(case when IdPregunta = 21 then RespuestaEmpleado end) EMP_R21,
	  max(case when IdPregunta = 22 then RespuestaEmpleado end) EMP_R22,
	  max(case when IdPregunta = 23 then RespuestaEmpleado end) EMP_R23,
	  max(case when IdPregunta = 24 then RespuestaEmpleado end) EMP_R24,
	  max(case when IdPregunta = 25 then RespuestaEmpleado end) EMP_R25,
	  max(case when IdPregunta = 26 then RespuestaEmpleado end) EMP_R26,
	  max(case when IdPregunta = 27 then RespuestaEmpleado end) EMP_R27,
	  max(case when IdPregunta = 28 then RespuestaEmpleado end) EMP_R28,
	  max(case when IdPregunta = 29 then RespuestaEmpleado end) EMP_R29,
	  max(case when IdPregunta = 30 then RespuestaEmpleado end) EMP_R30,
	  max(case when IdPregunta = 31 then RespuestaEmpleado end) EMP_R31,
	  max(case when IdPregunta = 32 then RespuestaEmpleado end) EMP_R32,
	  max(case when IdPregunta = 33 then RespuestaEmpleado end) EMP_R33,
	  max(case when IdPregunta = 34 then RespuestaEmpleado end) EMP_R34,
	  max(case when IdPregunta = 35 then RespuestaEmpleado end) EMP_R35,
	  max(case when IdPregunta = 36 then RespuestaEmpleado end) EMP_R36,
	  max(case when IdPregunta = 37 then RespuestaEmpleado end) EMP_R37,
	  max(case when IdPregunta = 38 then RespuestaEmpleado end) EMP_R38,
	  max(case when IdPregunta = 39 then RespuestaEmpleado end) EMP_R39,
	  max(case when IdPregunta = 40 then RespuestaEmpleado end) EMP_R40,

	  max(case when IdPregunta = 41 then RespuestaEmpleado end) EMP_R41,
	  max(case when IdPregunta = 42 then RespuestaEmpleado end) EMP_R42,
	  max(case when IdPregunta = 43 then RespuestaEmpleado end) EMP_R43,
	  max(case when IdPregunta = 44 then RespuestaEmpleado end) EMP_R44,
	  max(case when IdPregunta = 45 then RespuestaEmpleado end) EMP_R45,
	  max(case when IdPregunta = 46 then RespuestaEmpleado end) EMP_R46,
	  max(case when IdPregunta = 47 then RespuestaEmpleado end) EMP_R47,
	  max(case when IdPregunta = 48 then RespuestaEmpleado end) EMP_R48,
	  max(case when IdPregunta = 49 then RespuestaEmpleado end) EMP_R49,
	  max(case when IdPregunta = 50 then RespuestaEmpleado end) EMP_R50,
	  max(case when IdPregunta = 51 then RespuestaEmpleado end) EMP_R51,
	  max(case when IdPregunta = 52 then RespuestaEmpleado end) EMP_R52,
	  max(case when IdPregunta = 53 then RespuestaEmpleado end) EMP_R53,
	  max(case when IdPregunta = 54 then RespuestaEmpleado end) EMP_R54,
	  max(case when IdPregunta = 55 then RespuestaEmpleado end) EMP_R55,
	  max(case when IdPregunta = 56 then RespuestaEmpleado end) EMP_R56,
	  max(case when IdPregunta = 57 then RespuestaEmpleado end) EMP_R57,
	  max(case when IdPregunta = 58 then RespuestaEmpleado end) EMP_R58,
	  max(case when IdPregunta = 59 then RespuestaEmpleado end) EMP_R59,
	  max(case when IdPregunta = 60 then RespuestaEmpleado end) EMP_R60,

	  max(case when IdPregunta = 61 then RespuestaEmpleado end) EMP_R61,
	  max(case when IdPregunta = 62 then RespuestaEmpleado end) EMP_R62,
	  max(case when IdPregunta = 63 then RespuestaEmpleado end) EMP_R63,
	  max(case when IdPregunta = 64 then RespuestaEmpleado end) EMP_R64,
	  max(case when IdPregunta = 65 then RespuestaEmpleado end) EMP_R65,
	  max(case when IdPregunta = 66 then RespuestaEmpleado end) EMP_R66,
	  max(case when IdPregunta = 67 then RespuestaEmpleado end) EMP_R67,
	  max(case when IdPregunta = 68 then RespuestaEmpleado end) EMP_R68,
	  max(case when IdPregunta = 69 then RespuestaEmpleado end) EMP_R69,
	  max(case when IdPregunta = 70 then RespuestaEmpleado end) EMP_R70,
	  max(case when IdPregunta = 71 then RespuestaEmpleado end) EMP_R71,
	  max(case when IdPregunta = 72 then RespuestaEmpleado end) EMP_R72,
	  max(case when IdPregunta = 73 then RespuestaEmpleado end) EMP_R73,
	  max(case when IdPregunta = 74 then RespuestaEmpleado end) EMP_R74,
	  max(case when IdPregunta = 75 then RespuestaEmpleado end) EMP_R75,
	  max(case when IdPregunta = 76 then RespuestaEmpleado end) EMP_R76,
	  max(case when IdPregunta = 77 then RespuestaEmpleado end) EMP_R77,
	  max(case when IdPregunta = 78 then RespuestaEmpleado end) EMP_R78,
	  max(case when IdPregunta = 79 then RespuestaEmpleado end) EMP_R79,
	  max(case when IdPregunta = 80 then RespuestaEmpleado end) EMP_R80,

	  max(case when IdPregunta = 81 then RespuestaEmpleado end) EMP_R81,
	  max(case when IdPregunta = 82 then RespuestaEmpleado end) EMP_R82,
	  max(case when IdPregunta = 83 then RespuestaEmpleado end) EMP_R83,
	  max(case when IdPregunta = 84 then RespuestaEmpleado end) EMP_R84,
	  max(case when IdPregunta = 85 then RespuestaEmpleado end) EMP_R85,
	  max(case when IdPregunta = 86 then RespuestaEmpleado end) EMP_R86,

	  --Enfoque Area
	  max(case when IdPregunta = 87 then RespuestaEmpleado end) ARE_1,
	  max(case when IdPregunta = 88 then RespuestaEmpleado end) ARE_2,
	  max(case when IdPregunta = 89 then RespuestaEmpleado end) ARE_3,
	  max(case when IdPregunta = 90 then RespuestaEmpleado end) ARE_4,

	  max(case when IdPregunta = 91 then RespuestaEmpleado end) ARE_5,
	  max(case when IdPregunta = 92 then RespuestaEmpleado end) ARE_6,
	  max(case when IdPregunta = 93 then RespuestaEmpleado end) ARE_7,
	  max(case when IdPregunta = 94 then RespuestaEmpleado end) ARE_8,
	  max(case when IdPregunta = 95 then RespuestaEmpleado end) ARE_9,
	  max(case when IdPregunta = 96 then RespuestaEmpleado end) ARE_10,
	  max(case when IdPregunta = 97 then RespuestaEmpleado end) ARE_11,
	  max(case when IdPregunta = 98 then RespuestaEmpleado end) ARE_12,
	  max(case when IdPregunta = 99 then RespuestaEmpleado end) ARE_13,
	  max(case when IdPregunta = 100 then RespuestaEmpleado end) ARE_14,
	  max(case when IdPregunta = 101 then RespuestaEmpleado end) ARE_15,
	  max(case when IdPregunta = 102 then RespuestaEmpleado end) ARE_16,
	  max(case when IdPregunta = 103 then RespuestaEmpleado end) ARE_17,
	  max(case when IdPregunta = 104 then RespuestaEmpleado end) ARE_18,
	  max(case when IdPregunta = 105 then RespuestaEmpleado end) ARE_19,
	  max(case when IdPregunta = 106 then RespuestaEmpleado end) ARE_20,
	  max(case when IdPregunta = 107 then RespuestaEmpleado end) ARE_21,
	  max(case when IdPregunta = 108 then RespuestaEmpleado end) ARE_22,
	  max(case when IdPregunta = 109 then RespuestaEmpleado end) ARE_23,
	  max(case when IdPregunta = 110 then RespuestaEmpleado end) ARE_24,

	  max(case when IdPregunta = 111 then RespuestaEmpleado end) ARE_25,
	  max(case when IdPregunta = 112 then RespuestaEmpleado end) ARE_26,
	  max(case when IdPregunta = 113 then RespuestaEmpleado end) ARE_27,
	  max(case when IdPregunta = 114 then RespuestaEmpleado end) ARE_28,
	  max(case when IdPregunta = 115 then RespuestaEmpleado end) ARE_29,
	  max(case when IdPregunta = 116 then RespuestaEmpleado end) ARE_30,
	  max(case when IdPregunta = 117 then RespuestaEmpleado end) ARE_31,
	  max(case when IdPregunta = 118 then RespuestaEmpleado end) ARE_32,
	  max(case when IdPregunta = 119 then RespuestaEmpleado end) ARE_33,
	  max(case when IdPregunta = 120 then RespuestaEmpleado end) ARE_34,
	  max(case when IdPregunta = 121 then RespuestaEmpleado end) ARE_35,
	  max(case when IdPregunta = 122 then RespuestaEmpleado end) ARE_36,
	  max(case when IdPregunta = 123 then RespuestaEmpleado end) ARE_37,
	  max(case when IdPregunta = 124 then RespuestaEmpleado end) ARE_38,
	  max(case when IdPregunta = 125 then RespuestaEmpleado end) ARE_39,
	  max(case when IdPregunta = 126 then RespuestaEmpleado end) ARE_40,
	  max(case when IdPregunta = 127 then RespuestaEmpleado end) ARE_41,
	  max(case when IdPregunta = 128 then RespuestaEmpleado end) ARE_42,
	  max(case when IdPregunta = 129 then RespuestaEmpleado end) ARE_43,
	  max(case when IdPregunta = 130 then RespuestaEmpleado end) ARE_44,

	  max(case when IdPregunta = 131 then RespuestaEmpleado end) ARE_45,
	  max(case when IdPregunta = 132 then RespuestaEmpleado end) ARE_46,
	  max(case when IdPregunta = 133 then RespuestaEmpleado end) ARE_47,
	  max(case when IdPregunta = 134 then RespuestaEmpleado end) ARE_48,
	  max(case when IdPregunta = 135 then RespuestaEmpleado end) ARE_49,
	  max(case when IdPregunta = 136 then RespuestaEmpleado end) ARE_50,
	  max(case when IdPregunta = 137 then RespuestaEmpleado end) ARE_51,
	  max(case when IdPregunta = 138 then RespuestaEmpleado end) ARE_52,
	  max(case when IdPregunta = 139 then RespuestaEmpleado end) ARE_53,
	  max(case when IdPregunta = 140 then RespuestaEmpleado end) ARE_54,
	  max(case when IdPregunta = 141 then RespuestaEmpleado end) ARE_55,
	  max(case when IdPregunta = 142 then RespuestaEmpleado end) ARE_56,
	  max(case when IdPregunta = 143 then RespuestaEmpleado end) ARE_57,
	  max(case when IdPregunta = 144 then RespuestaEmpleado end) ARE_58,
	  max(case when IdPregunta = 145 then RespuestaEmpleado end) ARE_59,
	  max(case when IdPregunta = 146 then RespuestaEmpleado end) ARE_60,
	  max(case when IdPregunta = 147 then RespuestaEmpleado end) ARE_61,
	  max(case when IdPregunta = 148 then RespuestaEmpleado end) ARE_62,
	  max(case when IdPregunta = 149 then RespuestaEmpleado end) ARE_63,
	  max(case when IdPregunta = 150 then RespuestaEmpleado end) ARE_64,

	  max(case when IdPregunta = 151 then RespuestaEmpleado end) ARE_65,
	  max(case when IdPregunta = 152 then RespuestaEmpleado end) ARE_66,
	  max(case when IdPregunta = 153 then RespuestaEmpleado end) ARE_67,
	  max(case when IdPregunta = 154 then RespuestaEmpleado end) ARE_68,
	  max(case when IdPregunta = 155 then RespuestaEmpleado end) ARE_69,
	  max(case when IdPregunta = 156 then RespuestaEmpleado end) ARE_70,
	  max(case when IdPregunta = 157 then RespuestaEmpleado end) ARE_71,
	  max(case when IdPregunta = 158 then RespuestaEmpleado end) ARE_72,
	  max(case when IdPregunta = 159 then RespuestaEmpleado end) ARE_73,
	  max(case when IdPregunta = 160 then RespuestaEmpleado end) ARE_74,
	  max(case when IdPregunta = 161 then RespuestaEmpleado end) ARE_75,
	  max(case when IdPregunta = 162 then RespuestaEmpleado end) ARE_76,
	  max(case when IdPregunta = 163 then RespuestaEmpleado end) ARE_77,
	  max(case when IdPregunta = 164 then RespuestaEmpleado end) ARE_78,
	  max(case when IdPregunta = 165 then RespuestaEmpleado end) ARE_79,
	  max(case when IdPregunta = 166 then RespuestaEmpleado end) ARE_80,
	  max(case when IdPregunta = 167 then RespuestaEmpleado end) ARE_81,
	  max(case when IdPregunta = 168 then RespuestaEmpleado end) ARE_82,
	  max(case when IdPregunta = 169 then RespuestaEmpleado end) ARE_83,
	  max(case when IdPregunta = 170 then RespuestaEmpleado end) ARE_84,
	  max(case when IdPregunta = 171 then RespuestaEmpleado end) ARE_85,
	  max(case when IdPregunta = 172 then RespuestaEmpleado end) ARE_86,

	  --Abiertas
	  max(case when IdPregunta = 173 then RespuestaEmpleado end) ESPECIAL_OPEN,
	  max(case when IdPregunta = 174 then RespuestaEmpleado end) CAMBIAR_OPEN,
	  max(case when IdPregunta = 175 then RespuestaEmpleado end) FORT_JEFE,
	  max(case when IdPregunta = 176 then RespuestaEmpleado end) OPORT_JEFE,
	  --DDL
	  max(case when IdPregunta = 177 then RespuestaEmpleado end) MOTIVA_TRAB,
	  max(case when IdPregunta = 178 then RespuestaEmpleado end) DEJAR_EMP,
	  max(case when IdPregunta = 179 then RespuestaEmpleado end) PRESION,

	  --Demograficos
	  max(case when IdPregunta = 180 then RespuestaEmpleado end) ANTIGÜEDADR,
	  max(case when IdPregunta = 181 then RespuestaEmpleado end) RANGO_EDADR,
	  max(case when IdPregunta = 182 then RespuestaEmpleado end) CONDICIONR,
	  max(case when IdPregunta = 183 then RespuestaEmpleado end) SEXOR,
	  max(case when IdPregunta = 184 then RespuestaEmpleado end) ACADEMICOR,

	  --Obtener los demografico de estructura GAFM respuestas
	  max(case when IdPregunta = 185 then (RespuestaEmpleado) end) as FUNCIONR,
	  max(case when IdPregunta = 186 then RespuestaEmpleado end) UNIDADR,
	  max(case when IdPregunta = 187 then RespuestaEmpleado end) DIRECCIORN,
	  max(case when IdPregunta = 188 then RespuestaEmpleado end) AREAR,
	  max(case when IdPregunta = 189 then RespuestaEmpleado end) DEPARTAMENTOR
	
	FROM EmpleadoRespuestas
		left JOIN Empleado ON EmpleadoRespuestas.IdEmpleado = Empleado.IdEmpleado
		left JOIN Perfil ON Empleado.IdPerfil = Perfil.IdPerfil
		left JOIN Departamento on Empleado.IdDepartamento = Departamento.IdDepartamento --DEPARTAMENTO ORIGEN
		left JOIN Area ON Departamento.IdArea = Area.IdArea
		left JOIN Company ON Area.CompanyId = Company.CompanyId
		left JOIN CompanyCategoria ON Company.IdCompanyCategoria = CompanyCategoria.IdCompanyCategoria
		left JOIN EstatusEncuesta ON Empleado.IdEmpleado = EstatusEncuesta.IdEmpleado
        inner JOIN BasesDeDatos ON Empleado.IdBaseDeDatos = BasesDeDatos.IdBasesDeDatos
		left JOIN SubDepartamento on Empleado.IdSubdepartamento = SubDepartamento.IdSubdepartamento
	WHERE Empleado.UnidadNegocio = 'turismo' and Empleado.IdBaseDeDatos = 1
	GROUP BY Empleado.IdEmpleado, Empleado.ApellidoPaterno, Empleado.ApellidoMaterno, 
		Empleado.Nombre,	Empleado.Puesto ,Empleado.FechaNacimiento, 
		Empleado.FechaAntiguedad, Empleado.Sexo, Empleado.Correo, 
		Empleado.TipoFuncion, Empleado.CondicionTrabajo, Empleado.GradoAcademico, 
		Empleado.EmpresaContratante, 
		Empleado.IdResponsableRH, Empleado.NombreResponsableRH, Empleado.IdJefe, 
		Empleado.NombreJefe, PuestoJefe, Empleado.IdResponsableEstructura, 
		Empleado.NombreResponsableEstructura, Empleado.ClaveAcceso, 
		Empleado.RangoAntiguedad, Empleado.RangoEdad, 
		Empleado.UnidadNegocio, Empleado.DivisionMarca, Empleado.AreaAgencia, Empleado.Depto, Empleado.Subdepartamento,
		EstatusEncuesta.Estatus , Empleado.EstatusEmpleado, EmpleadoRespuestas.IdEmpleado--, DEPTOX.Nombre, PERFX.Descripcion, UNIDADX.Descripcion, DIRECCIONX.CompanyName, AREAX.Nombre
		ORDER BY EmpleadoRespuestas.IdEmpleado ASC

select * from preguntas where idEncuesta = 1