<h3>Formulario de contacto</h3>
<div class="col-6">
    <form>
        <div class="form-group">
            <label>Correo electronico: </label>
            <div class="col-4">
                <input type="text" minlength="5" required />
            </div>
        </div>
        <div class="form-group">
            <label>Mensaje: </label>
            <div class="col-4">
                <textarea rows="4" cols="" require></textarea>
            </div>
        </div>
        <div class="form-group">
            <label>Correo electronico: </label>
            <div class="col-4">
                <input type="submit" value="Enviar" />
            </div>
        </div>
    </form>
</div>