 <section id="slider">
        <div id="carouselAutofin" class="carousel slide carousel-fade" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselAutofin" data-slide-to="0" class="active"></li>
            <li data-target="#carouselAutofin" data-slide-to="1"></li>
            <li data-target="#carouselAutofin" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" align="center">
            <div class="carousel-item active">
              <img src="https://via.placeholder.com/1920x900" class="img-fluid d-none d-sm-none d-md-block" alt="Slide 1 large">
              <img src="https://via.placeholder.com/800x900" class="img-fluid d-block d-sm-block d-md-none" alt="Slide 1 small">
            </div>
            <div class="carousel-item">
              <img src="https://via.placeholder.com/1920x900" class="img-fluid d-none d-sm-none d-md-block" alt="Slide 2 large">
              <img src="https://via.placeholder.com/800x900" class="img-fluid d-block d-sm-block d-md-none" alt="Slide 2 small">
            </div>
            <div class="carousel-item">
              <img src="https://via.placeholder.com/1920x900" class="img-fluid d-none d-sm-none d-md-block" alt="Slide 3 large">
              <img src="https://via.placeholder.com/800x900" class="img-fluid d-block d-sm-block d-md-none" alt="Slide 3 small">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselAutofin" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselAutofin" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </section>
