<style type="text/css">
    body {
        /*overflow-y: auto;
        overflow-x: hidden;*/
        overflow-y: auto;
        overflow-x: auto;
    }
    .page-main{
        max-width: 100%!important;
        background: #ffcc00;
        padding-left: 0px;
        padding-right: 0px;
    }
    footer {
        /*position: relative;
        width: 100%;*/
        position: fixed;
        bottom: 0;
        width: 100%;
    }
</style>