<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
?>
<?php if ($customerSession->isLoggedIn()) { ?>
<ul class="navbar-nav ml-auto mt-2 mt-lg-0">    
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('/') ?>">Inicio <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Productos
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <a class="dropdown-item"  href="<?= $this->getUrl('auto') ?>">Auto</a>
                  <a class="dropdown-item" href="<?= $this->getUrl('casa') ?>">Casa</a>	          
                  
	        </div>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Clientes
	        </a>
	        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <li><a class="dropdown-item" href="<?php echo $this->getUrl("clientes-auto");?>">Auto</a></li>
	          <li><a class="dropdown-item" href="<?php echo $this->getUrl("clientes-casa");?>">Casa</a></li>
	        </ul>
	      </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuPublication" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Publicación
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuPublication">
                    <li class="dropright"><a class="dropdown-item" >Adjudicados</a>
                        <ul>
                            <li>
                                <a href="<?php echo $this->getUrl("adjudicados_casa");?>">Casa</a>                            
                            </li>
                            <li> 
                                <a href="<?php echo $this->getUrl("adjudicados_auto");?>">Auto</a>                           
                            </li>
                        </ul>
                    </li>
                    <li class="dropright"><a class="dropdown-item" >Lista de precios</a>
                        <ul>
                            <li>
                                <a href="<?php echo $this->getUrl("listaprecios_casa");?>">Casa</a>                           
                            </li>
                            <li>
                                <a href="<?php echo $this->getUrl("listaprecios_auto");?>">Auto</a>                            
                            </li>
                        </ul>                                
                    </li>
                </ul>
            </li>
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('contact') ?>">Contacto</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('bolsa-de-trabajo') ?>" >Bolsa de trabajo</a>
	      </li>
	    </ul>
	      <a class="btn btn-success btn-login" href="<?= $this->getUrl('customer/account/logout') ?>">Cerrar sesión</a>
<?php }else {?>
<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('/') ?>">Inicio <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Productos
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <a class="dropdown-item"  href="<?= $this->getUrl('auto') ?>">Auto</a>
                  <a class="dropdown-item" href="<?= $this->getUrl('casa') ?>">Casa</a>	          
                  
	        </div>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Clientes
	        </a>
	        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <li><a class="dropdown-item" href="<?php echo $this->getUrl("clientes-auto");?>">Auto</a></li>
	          <li><a class="dropdown-item" href="<?php echo $this->getUrl("clientes-casa");?>">Casa</a></li>
	        </ul>
	      </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuPublication" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Publicación
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuPublication">
                    <li class="dropright"><a class="dropdown-item" >Adjudicados</a>
                        <ul>
                            <li>
                                <a href="<?php echo $this->getUrl("adjudicados_casa");?>">Casa</a>                            
                            </li>
                            <li> 
                                <a href="<?php echo $this->getUrl("adjudicados_auto");?>">Auto</a>                           
                            </li>
                        </ul>
                    </li>
                    <li class="dropright"><a class="dropdown-item" >Lista de precios</a>
                        <ul>
                            <li>
                                <a href="<?php echo $this->getUrl("listaprecios_casa");?>">Casa</a>                           
                            </li>
                            <li>
                                <a href="<?php echo $this->getUrl("listaprecios_auto");?>">Auto</a>                            
                            </li>
                        </ul>                                
                    </li>
                </ul>
            </li>
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('contact') ?>">Contacto</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->getUrl('bolsa-de-trabajo') ?>" >Bolsa de trabajo</a>
	      </li>
	    </ul>
	      <a class="btn btn-success btn-login" href="<?= $this->getUrl('customer/account/login') ?>">Iniciar sesión</a>
<?php } ?>